### ISSUE TITLE
'submit jobs' tab - clear previous inputs

### ISSUE THREAD

**Issue by jayoung** [FredHutch/shiny-cromwell#10]
hi,

let's say I first validate workflow A  - I upload a WDL and an input JSON file (e.g. `diy-cromwell-server/testWorkflows/tg-wdl-VariantCaller`). That goes fine.

I next want to validate workflow B, a workflow that doesn't need any input JSON  (e.g. `diy-cromwell-server/testWorkflows/helloHostname`).   I don't think there's a way to clear the previously uploaded JSON.  Because workflow A's JSON is still in memory, the validation fails ("WARNING: Unexpected input provided: Panel_BWA_GATK4_Annovar.referenceGenome (expected inputs: [])").    

I think I have to reload the shiny app in my browser, reconnect to the server, THEN revalidate workflow B (this time it succeeds, when there's no JSON uploaded).  

That's a bit of a pain - would it be easy to add a 'clear input' button to parts or all of the 'submit jobs' tab?

thanks!

Janet

**Comment by sitapriyamoorthi** [comment]
@sckott @vortexing

**Comment by sitapriyamoorthi** [comment]
![Screenshot 2023-12-14 at 9 48 02 AM](https://github.com/FredHutch/shiny-cromwell/assets/23532136/75e0578e-e428-4ba4-b7e7-40ae76151853)

**Comment by vortexing** [comment]
I have looked to fix this before and the outcome of my searches and work was that this was a failure of shiny apps generally.  I seriously doubt that that's truly true but the solution to this requires more than a cursory "set defaults differently" solution.  This one is important to fix though - I personally can't stand this behavior.

**Comment by vortexing** [comment]
This is annoying enough that it might be good to wire in a "reset button" in this block that resets all the fileInputs to NULL, OR a reset button for EACh of the upload fields so you can reset them individually.  https://stackoverflow.com/questions/44203728/how-to-reset-a-value-of-fileinput-in-shiny. Thoughts @sckott and @seankross?   Perhaps I can take a sprint if this is annoying to actually do.

**Comment by sckott** [comment]
I believe i have some draft code locally already for this .. will push up soon

**Comment by sckott** [comment]
(handled in `getwilds/shiny-cromwell@dev`)
