### ISSUE TITLE
no workflow labels in table

### ISSUE THREAD

**Issue by vortexing** [FredHutch/shiny-cromwell#106]
The user defined workflow labels no longer show up in the "Workflows Run" table in the app.

**Comment by tefirman** [comment]
Just noticed this as well, the label only shows up in the "Workflow Details" table when you select one of the jobs in "Workflows Run". And even then, you have to scroll all the way to the right (see screenshot below). Wondering if we should also make it a searchable field at the top along with history, name, and status? And allow partial matches? (i.e. if I submitted "testrun_1" and "testrun_2", I should be able to search for "testrun_" and see both)
![PROOFWorkflowDetails](https://github.com/FredHutch/shiny-cromwell/assets/37599954/129c3408-763c-4098-b76b-9190a1cd4c0d)

**Comment by sckott** [comment]
Hey @vortexing @tefirman it's been a month since this opened. Seems like the details of what you want are still up in the air. Any further thoughts on what you want this to look like in the tracking page?

**Comment by tefirman** [comment]
Hey @sckott ! Thanks for following up on this! I think I was envisioning moving the "Label" column from the "Workflow Description" table up to the "Workflows Run" table (see screenshot below), maybe renamed as "workflow_label" just to the right of "workflow_name"? This way if I submit multiple simultaneous analyses, I can easily differentiate between them without having to select and scroll down for each one. How much lift would something like that require?

<img width="1164" alt="image" src="https://github.com/FredHutch/shiny-cromwell/assets/37599954/90ae42e7-4007-466e-a89b-3261626d5849">

**Comment by sckott** [comment]
I think it'd be easy, but I haven't checked yet. I'll have a look see

**Comment by sckott** [comment]
@tefirman PR at https://github.com/FredHutch/shiny-cromwell/pull/117 to look at
