### ISSUE TITLE
Allow for partial match in workflow name search

### ISSUE THREAD

**Issue by tefirman** [FredHutch/shiny-cromwell#112]
- In the "Track Jobs" tab of PROOF, we allow for the search of workflows by name using the "Filter for workflows with name:" text box. However, you need to match the workflow name **exactly** for it to work.
- It would be helpful to allow for some sort of wildcard functionality, where it displays all workflows with at least a partial match of what was entered.
- To start, we could even just do a "startswith" functionality, e.g. a search of "hello" would populate all workflows with names like "helloWorld" and "helloFredHutch", or maybe a "contains" functionality, e.g. a search of "bar" would find both "foobar" and "barometric".
- This would be particularly relevant if we add a search for workflow labels as well.

**Comment by sckott** [comment]
Working on this locally ...

**Comment by sckott** [comment]
on branch `workflow-name-select`

**Comment by sckott** [comment]
Note that this was done on a branch but then undone b/c it needs a rethink
