### ISSUE TITLE
app says "Your server is not up" when it is

### ISSUE THREAD

**Issue by dtenenba** [FredHutch/shiny-cromwell#114]
I was trying to do a one-person stress test and I had the PROOF app open in 3 browser tabs. I had a proof server running and I was logged into each tab and I had uploaded a simple WDL to each in the Submit Jobs tab. 
I clicked Submit Job in the first tab and it worked fine, and then clicked the same button in the other 2 tabs right away. In both tabs I got the message `Error: Your server is not up!` and this appeared in the app logs:

```
Error in : Your server is not up!
<Anonymous>
stop
stop_safe
stop_safe_loggedin_serverup
renderPrint [/srv/shiny-server/server.R#409]
func
renderFunc
output$submissionResult
runApp
```

But then if I go to the PROOF Server tab, in all 3 tabs, it says my server is RUNNING.

I wonder if the code is consulting a local or session variable to determine whether the server is running (when submitting a workflow), and since the server was started in another session/tab, it doesn't realize there is a running server. Maybe instead it could consult the PROOF API.
On the other hand, this is a bit of a contrived situation and I am not sure how important it is to track this down.

**Comment by sckott** [comment]
We're calling the `rcromwell` function to get the Cromwell server version running https://github.com/FredHutch/shiny-cromwell/blob/main/app/proof.R#L26 as a way to test if the server is up or not. That's within a try catch so we'd have to remove that trycatch and let the error(s) surface to see what's going on.
