### ISSUE TITLE
Visualization of WDL workflow (as a workflow diagram)

### ISSUE THREAD

**Issue by sitapriyamoorthi** [FredHutch/shiny-cromwell#115]
It might be "user-friendly" to consider adding somewhere a translation of the WDL inputted by the user into a workflow diagram.
Why? Cause this could provide a visual interpretation of the user's workflow, show dependencies of tasks, etc. This could also be helpful to those users who are using pre-built WDL to understand the map of the workflows, particularly those that are highly complex. This is definitely a nice to have. There already exist tools that do this elsewhere.

**Comment by sckott** [comment]
Just to pull the links out for the tools:
- https://github.com/FredHutch/wdl2dag
- https://github.com/chanzuckerberg/miniwdl-viz
- https://github.com/miniwdl-ext/wdlviz

**Comment by tefirman** [comment]
Wondering if this is an addition to the "Validate" tab or if this merits a new tab, e.g. "Visualize"? Just spit-balling...

**Comment by sckott** [comment]
Seems appropriate for validate tab IF we could somehow visualize a bad WDL file, but if we can not do that, then seems more appropriate as a separate use case of just visualizing, so a separate tab.

**Comment by tefirman** [comment]
This was fixed in https://github.com/FredHutch/shiny-cromwell/pull/125 and https://github.com/FredHutch/shiny-cromwell/pull/133, not sure why it wasn't closed. Closing now.
