### ISSUE TITLE
Persist User Login with Cookies

### ISSUE THREAD

**Issue by tefirman** [FredHutch/shiny-cromwell#118]
Every time the PROOF page is refreshed, it automatically logs out the user and they have to log in again. Not critical, but definitely annoying, wondering if we can persist the login via cookies or something. Discussed this with Scott previously, but personally not 100% sure exactly how to do this.

**Comment by sckott** [comment]
I played around with cookies a ways back, but gave up on it for what reason I don't remember. 

At the time `shinyauthr` had some cookie functionality in it, and there's https://github.com/shinyworks/cookies

**Comment by sckott** [comment]
Playing with this locally. May have something soon to look at
