### ISSUE TITLE
Server up but, validate tab says its not

### ISSUE THREAD

**Issue by sitapriyamoorthi** [FredHutch/shiny-cromwell#119]
Started a PROOF server. Got the email saying PROOF server is ready. Tried to validate a workflow but validate tab says my server is not ready. Logging out and re-logging back in solved the issue. 

![Screenshot 2024-08-07 at 1 16 27 PM](https://github.com/user-attachments/assets/fc32b774-d4ce-4fae-a992-958037762cb3)
![Screenshot 2024-08-07 at 1 16 35 PM](https://github.com/user-attachments/assets/881739f5-7f80-4de1-8f3f-d19d721b7b83)
![Screenshot 2024-08-07 at 1 16 46 PM](https://github.com/user-attachments/assets/e3008122-8bda-4b71-8b27-0fe9d0021233)
![Screenshot 2024-08-07 at 1 21 46 PM](https://github.com/user-attachments/assets/489d4e17-bfcd-4edc-892b-a54d1964a118)

**Comment by sckott** [comment]
Thanks Sita, i'll see if I can replicate and then ping back here

**Comment by vortexing** [comment]
@sckott one thing that is important is that the PROOF shiny app says when a server is live when a job is started on a gizmo node for the server.  But the server takes a minute to start up before the API is available for communication with the app.  

One thing that might be useful is somehow registering both when a server job is kicked off AND when the API is open for business.  This could be an occasional polling of the API until a valid response is obtained (that's what I used to use the function that checks for the cromwell version for - just to see if the API was available).  It could poll until it gets a valid response and THEN tell the user the server is on and send that email.

**Comment by vortexing** [comment]
Also, @sitapriyamoorthi  and @sckott  the above behavior is often not actually solved by "a user doing x" it's actually solved by time passing and the API becoming available to hit with the app.

**Comment by sitapriyamoorthi** [comment]
@vortexing i think thats a good approach. Because that might be true representation of that the server is ready to accept jobs when API is open for business!

**Comment by sckott** [comment]
A few thoughts

- The behavior of the PROOF API isn't always the same as we've all experienced. So this plays a role here probably
- We do currently check that the Cromwell API started by the PROOF API is up. The same set of checks are used in the modal that is used to start a server and throughout the app to make sure the API is up. 
- @sitapriyamoorthi could you share the exact sequence of events that made this happen? 
  - You logged in to the app?
  - Then went to server tab?
  - Did you wait for the modal to go away after starting a server? 
  - etc.

**Comment by sitapriyamoorthi** [comment]
Hey @sckott following up here is the series of events:

1. Logged into app
2. Started server
3. Waited for server to start up (aka the details of the file paths etc get loaded up)
4. Waited for me to get the email
5. Headed to the validation tab to upload the wdl and json
6. Hit validate 
7. Said my server wasnt ready
8. logged out and logged back in 
9. tried the validate step again ... and it worked!

Curious if you could explain what you mean by the behavior of the PROOF API isnt always the same?

**Comment by sckott** [comment]
Thanks for that Sita. That sequence of events makes me think the cause was this issue of the PROOF infrastructure not always behaving the same - not totally sure, but it smells like that. I haven't been able to reproduce this issue, so hard to say for sure 🤷🏽 

> Curious if you could explain what you mean by the behavior of the PROOF API isnt always the same?

Since PROOF runs on shared infrastructure I've heard from Dan that sometimes things are slower than normal. If e.g., PROOF was all run on a dedicated server we'd expect behavior to always be the same.

**Comment by sitapriyamoorthi** [comment]
Issue persists
![Screenshot 2024-11-13 at 10 32 54 AM](https://github.com/user-attachments/assets/e8fae6f2-b123-44ff-90ec-ed2d8d7c32c1)
![Screenshot 2024-11-13 at 10 32 44 AM](https://github.com/user-attachments/assets/9177c3ca-5ed5-4df0-8964-4bcdc34cec40)
