### ISSUE TITLE
Visualize WDLs in the app

### ISSUE THREAD

**Issue by sckott** [FredHutch/shiny-cromwell#122]
relates to #85 #120

See discussion from https://github.com/FredHutch/shiny-cromwell/pull/120#issuecomment-2282841279 onwards in that issue for context. 

There's a few outstanding questions for this:

1. Where would it make the most sense to put this in the app?
2. How do we technically parse and display the WDL? After a deep dive, I'm still not sure best route, but here's some notes:
  - Wrap Rust in R?
    - https://github.com/jdidion/wdl-rs
    - https://crates.io/crates/wdl
  - Use a Python tool?
    - https://github.com/miniwdl-ext/wdlviz
    - https://github.com/w-gao/wdl-viewer
    - https://github.com/chanzuckerberg/miniwdl-viz - this may be the best option as it can output a mermaid.js format, which we could then I think visuzliae as JS, similar to visualizing the json of inputs. in terms of how to do this, perhaps we'd see if the proof API could have a route that runs this module and gives back the data to then visualize on the app side
  - Use the output of the Cromwell route `/api/womtool/v1/describe`? Not clear how we'd use this to visualize
  - R
    - The package `DiagrammeR` can maybe output mermaid.js format? https://rich-iannone.github.io/DiagrammeR/articles/graphviz-mermaid.html

**Comment by tefirman** [comment]
This was fixed in #125 and #133, not sure why it wasn't closed. Closing now.
