### ISSUE TITLE
Email notifications?

### ISSUE THREAD

**Issue by sckott** [FredHutch/shiny-cromwell#13]
(via a call with Sita today)

Sita said:

> Is there way to maybe send a notification to the user when there server times out? Sometimes I forget when I kicked on my server

I think we could do this, though it's not not complex. 😉 

(i think) we'd need something (some server space, FH infra or a tiny EC2 VM) to keep track of things and do stuff:

- be able to access all users that are using the app
- be allowed to send emails to those users
- at simplest run a cron job every X hours/days to check if an email should be sent

The title of the issue is broad since I imagine there's more things than the original question which might want an email notification. 

FH has pretty aggressive email filtering though, so I wouldn't be surprised if we had some headache getting emails to not get blocked . 

cc @sitapriyamoorthi

**Comment by sckott** [comment]
@vortexing i'm guessing this is a lower priority item in the grand scheme of things. thoughts?

**Comment by vortexing** [comment]
This would be a likely large effort with relatively low adoption/payoff.  Most people likely don't want to get an email, but would rather see when they log into the app, some evidence that they already have a server running.  Given the repairs with the server spin-up and monitoring from SciComp, I'd guess this actually will no longer be needed once you can go to proof.fredhutch.org and see whether your server is still running or if you need a new one.

**Comment by sckott** [comment]
Sounds right

**Comment by vortexing** [comment]
@sckott this feels like a proofapi issue to me now rather than a shiny-cromwell issue.  No?

**Comment by tefirman** [comment]
As @vortexing mentions above, I think this feature would be too large of an effort with too little of a payoff. It's easy enough to see if your server is still running via the "PROOF Server" tab, and if it's not, starting up another one is a click of a button on the same page. Closing this as "not planned".
