### ISSUE TITLE
Change copy button to copy workflow id on click?

### ISSUE THREAD

**Issue by sckott** [FredHutch/shiny-cromwell#131]
via chat with @codebeaker 

Suggested as a feature via chats with app users by Sonu. 

I think pretty easy to do, can test out soon and see what it look like

**Comment by tefirman** [comment]
@sckott @codebeaker -- Could you expand on what this means? Are you saying that the button should have the words "Copy Workflow ID" on it instead of the page icon?

**Comment by sckott** [comment]
hmm, I don't remember actually. I thought this was enough context but maybe not. Do you remember @codebeaker ?

**Comment by sckott** [comment]
let's close this

**Comment by MinecraftEarthVillage** [comment]
不要下载我前段时间发的文件，那不是我发的，是另一个人控制我，如果你使用了这个病毒文件，你也会被控制，并且疯狂转发这个病毒
Don't download the file I sent some time ago, it wasn't me, but another person controlled me. If you use this virus file, you will also be controlled and forward this virus crazily.
