### ISSUE TITLE
Modularize code?

### ISSUE THREAD

**Issue by sckott** [FredHutch/shiny-cromwell#15]
This approach (https://mastering-shiny.org/scaling-modules.html) seems like it would be useful to make the code here easier to maintain and understand moving forward. There's enough complexity it may be warranted.

**Comment by sckott** [comment]
Shiny now supports R code inside of an R directory just like an R package, see https://shiny.posit.co/r/articles/build/app-formats/ - should do this most likely to modularize codee

**Comment by tefirman** [comment]
This is definitely a v2.0 question, moving to v2.0 milestone and setting as low priority for now.

**Comment by sckott** [comment]
We could close as this is shiny specific. The concept of modular code is a good one to keep in mind though as we switch away from shiny
