### ISSUE TITLE
WDL Viewer not displaying the WDL

### ISSUE THREAD

**Issue by sitapriyamoorthi** [FredHutch/shiny-cromwell#150]
I have a large-ish WDL that I am testing out but looks like the WDL tab is not working? I get a blank screen (see below)
![Screenshot 2024-10-21 at 10 49 38 AM](https://github.com/user-attachments/assets/1fc2ebb0-6afc-40c4-ad74-dcda6eb2d64a)

**Comment by sckott** [comment]
Thanks @sitapriyamoorthi ! 

Can you try on dev and see if you get the same thing?

**Comment by sitapriyamoorthi** [comment]
Dev is not letting me start a PROOF server currently

**Comment by sitapriyamoorthi** [comment]
@sckott works there

**Comment by sckott** [comment]
ok great. glad it works - do you prefer to use prod now or dev? if prod I can see about fixing it, but if it works in dev maybe just forget about prod for now.

**Comment by sckott** [comment]
> Would be nice to be able to download and save a copy as pdf or something!

Sure can probably do that. What is more useful? An image or a pdf?

**Comment by sitapriyamoorthi** [comment]
I can work with both so if the intention is to upgrade dev->prod eventually its fine i could go back and forth. Also I think PDFs are better

**Comment by sckott** [comment]
Ok i'll close this and open an issue for the pdf download

**Comment by sckott** [comment]
https://github.com/FredHutch/shiny-cromwell/issues/151
