### ISSUE TITLE
Local Instance Troubles

### ISSUE THREAD

**Issue by tefirman** [FredHutch/shiny-cromwell#153]
I can't seem to run this app locally using any of the methods in the README.
- When I tried to run via `make run_docker`, it complains about a missing `.my.cnf` file.
- When I tried to run via `make branch=workflow-name-select run_branch`, it ran out of memory on my local machine and then logged me out of nexus-registry.fredhutch.org
- When I tried to install the necessary packages using `pak::pak`, it produced an "access denied" error:
<img width="859" alt="image" src="https://github.com/user-attachments/assets/621d7e3a-471c-4ef6-aae5-b15be01bf018">
Are you able to run a local instance on your machine with `run_branch`? It very well could just be my machine, but I'm having a hard time, seems like running a local instance has gotten much more complex. I can always just merge this into dev and test it there, I just want to understand what's happening here.

_Originally posted by @tefirman in https://github.com/FredHutch/shiny-cromwell/issues/148#issuecomment-2430857432_

**Comment by tefirman** [comment]
@sckott, sounds like this was isolated to those changes that were retracted, you think it's okay to close this?

**Comment by sckott** [comment]
I think so yes closing sounds good
