### ISSUE TITLE
update header with Fred Hutch branding

### ISSUE THREAD

**Issue by codebeaker** [FredHutch/shiny-cromwell#154]
![Fred-Hutch-Logo-Primary-Reverse](https://github.com/user-attachments/assets/54b46ce9-63b6-466d-93e5-d09f441b0753)
We should update the header to:
1) Have the Fred Hutch logo (so it looks like [reverse primary white on black](https://brand.fredhutch.org/d/KPkLjsrU6mM4/brand-guidelines#/visual-elements/logo))
2) Have a black background
3) Have the 'Welcome' screen content be linked from 'PROOF' and get rid of the word 'Welcome'
4) Change 'Resources' to 'Help' and move it to the end
[Figma ](https://www.figma.com/design/TB7G3FakSSZOMNW1GALi1x/proof-bs?node-id=477-26&t=0zdNr3XYbr0JbH2C-1)

**Comment by sckott** [comment]
- [ ] 1...
- [ ] 1...
- [ ] 1...
- [ ] 1...

**Comment by sckott** [comment]
on branch `ui-changes`
