### ISSUE TITLE
update text on the landing page

### ISSUE THREAD

**Issue by codebeaker** [FredHutch/shiny-cromwell#155]
1) Change 'This' to "PROOF (Production Onramp for Optimization and Feasibility)"
2) Update 'Resources page' to 'Help'/'Get help'/whatever variation we go with

[figma](https://www.figma.com/design/TB7G3FakSSZOMNW1GALi1x/proof-bs?node-id=477-26&t=0zdNr3XYbr0JbH2C-1)

**Comment by sckott** [comment]
- [ ] change this text

2. is already in #154

**Comment by sckott** [comment]
on branch `ui-changes`
