### ISSUE TITLE
Update Resources/Help content

### ISSUE THREAD

**Issue by codebeaker** [FredHutch/shiny-cromwell#156]
1) Change top 'resources' header to "Getting Help with PROOF and WDL at Fred Hutch"
2) Change bottom 'resources' header to "Some Resources for Using Cromwell"
3) Add any other help content like how to email us, link to file an issue on github, etc.
[Figma](https://www.figma.com/design/TB7G3FakSSZOMNW1GALi1x/proof-bs?node-id=481-66&t=UeLdktFOgvSwMEnp-1)

**Comment by sckott** [comment]
- [ ] change wording of top most header on help page
- [ ] change wording of bottom most header on help page
- [ ] add taken out bits on github issues and such

**Comment by sckott** [comment]
on branch `ui-changes`
