### ISSUE TITLE
Updates to server page

### ISSUE THREAD

**Issue by codebeaker** [FredHutch/shiny-cromwell#157]
1) Add a sentence that stopping your PROOF server will not stop your job
2) Add some kind of loading indicator for when some page content has loaded but not server info
3) make the styles for "Note" consistent: bold with colon works well 
[Figma](https://www.figma.com/design/TB7G3FakSSZOMNW1GALi1x/proof-bs?node-id=485-113&t=UeLdktFOgvSwMEnp-1)

**Comment by sckott** [comment]
- [ ] Add a sentence that stopping your PROOF server will not stop your job
- [ ] Add some kind of loading indicator for when some page content has loaded but not server info
- [ ] make the styles for "Note" consistent: bold with colon works well

**Comment by sckott** [comment]
on branch `ui-changes`
