### ISSUE TITLE
Submit page changes

### ISSUE THREAD

**Issue by codebeaker** [FredHutch/shiny-cromwell#158]
1) Disable submit button when nothing uploaded or after something submitted until form is reset or something else uploaded
2) Make submit button green (same as 'start server') when enabled
3) give button a loading state when submission in progress (spinny disk, faded out)
4) Move workflow id and status info (when it appears) to underneath submit button, above reset form button
[Figma](https://www.figma.com/design/TB7G3FakSSZOMNW1GALi1x/proof-bs?node-id=486-116&t=UeLdktFOgvSwMEnp-1)

**Comment by sckott** [comment]
- [ ] Disable submit button when nothing uploaded or after something submitted until form is reset or something else uploaded
- [ ] Make submit button green (same as 'start server') when enabled
- [ ] give button a loading state when submission in progress (spinny disk, faded out)
- [ ] Move workflow id and status info (when it appears) to underneath submit button, above reset form button

**Comment by sckott** [comment]
> Disable submit button after something submitted until form is reset or something else uploaded

@codebeaker I'm not sure i can do this. okay to leave out?

**Comment by sckott** [comment]
> give button a loading state when submission in progress (spinny disk, faded out)

@codebeaker this happens usually quickly though in my experience, BUT have you heard from others that it can be slow enough to warrant a spinner?

**Comment by codebeaker** [comment]
The issue with submit wasn't the speed, it was that it's not clear that you've actually submitted the WDL because the screen doesn't change if the confirmation info is above the fold. Changing the button load state would indicate that something happened plus it would be consistent with a loading state for buttons that take longer like the track workflows button. I feel like that's more important especially if we're not disabling the submit button. Thoughts?

**Comment by sckott** [comment]
@codebeaker 

okay i did this

> Disable submit button after something submitted until form is reset or something else uploaded

but i still don't think we need a spinner UNLESS we find out that there's some cases where submitting the job takes long enough in my mind to have one , e.g., 5 or more seconds
