### ISSUE TITLE
Updates to Track Workflows page

### ISSUE THREAD

**Issue by codebeaker** [FredHutch/shiny-cromwell#159]
1) Add a loading indicator for when page content is loading
2) Have the title bar of a card show workflowname (label1, label2) instead of workflow id
3) move workflow Id to bottom left of card
4) have loading state for 'workflow details' button for when you have clicked it and it is still loading
[Figma](https://www.figma.com/design/TB7G3FakSSZOMNW1GALi1x/proof-bs?node-id=486-269&t=UeLdktFOgvSwMEnp-1)

**Comment by sckott** [comment]
- [ ] Add a loading indicator for when page content is loading
- [ ] Have the title bar of a card show workflowname (label1, label2) instead of workflow id
- [ ] move workflow Id to bottom left of card
- [ ] have loading state for 'workflow details' button for when you have clicked it and it is still loading

**Comment by sckott** [comment]
> Add a loading indicator for when page content is loading

There's nothing provided out of the box for this, so we'd have to roll our own. Not sure how to do it yet. These may help along lines of detecting when a UI element has rendered - as in, we can show a loading card with some kind of spinner or so, and then remove it once the cards with data are ready

- https://stackoverflow.com/questions/77601277/performing-an-action-in-shiny-after-an-output-is-rendered
- https://stackoverflow.com/questions/43665863/how-to-observe-dynamically-rendered-ui
- https://forum.posit.co/t/call-back-when-shiny-renderui-is-done/99973/8
- https://github.com/rstudio/shiny/issues/3348
