### ISSUE TITLE
Make connected to DIY server button clear

### ISSUE THREAD

**Issue by sckott** [FredHutch/shiny-cromwell#16]
It would be neat if we could change the Connect to Server button after connecting. Currently it's:

![Screenshot](https://github.com/FredHutch/shiny-cromwell/assets/577668/e56c2b6b-5011-4503-a8e1-597241719e1b)

Change to something like:

![Screenshot 2023-12-15 at 10 36 58 AM](https://github.com/FredHutch/shiny-cromwell/assets/577668/c19c1941-68ca-46da-ac9e-408d95d10edf)

**Comment by vortexing** [comment]
@sckott do you think this, or something like it (a text box that only is displayed upon connection) would be a low lift?  If a very low lift solution could be done, I'd like to prioritize it b/c I think this will be very helpful for newbies having a positive experience.

**Comment by sckott** [comment]
no longer needed since we now replace the enter url button with a exit button (that's red, for now at least)
