### ISSUE TITLE
Dev UI: Wont let me delete my server

### ISSUE THREAD

**Issue by sitapriyamoorthi** [FredHutch/shiny-cromwell#176]
I had a server running tried to delete it to allow for testing of the new UI. 
The popup allows me to type out delete me but wont let me click the button to stop server
![Screenshot 2024-11-04 at 9 46 09 AM](https://github.com/user-attachments/assets/329b4afc-c109-4445-a015-5410ec008b0f)

**Comment by dtenenba** [comment]
Maybe just a yes/no confirmation, which could indicate that you can always re-create a server if you need to. 
Typing in "delete me" seems like overkill, which would be appropriate for a truly destructive operation, which this is no.

**Comment by sckott** [comment]
Okay, this is done - on dev url now. Removed the textinput. Just went without anything to make it easy since it truly is non-destructive

**Comment by sitapriyamoorthi** [comment]
It looks like this works! Wohoo! Going to close this issue!
