### ISSUE TITLE
Split validate and submit tabs

### ISSUE THREAD

**Issue by sitapriyamoorthi** [FredHutch/shiny-cromwell#18]
Can we consider splitting the validate and submit tabs. User has to re-input the WDL and JSON files anyways at the bottom for submission. @vortexing 
![Screenshot 2023-12-14 at 9 47 43 AM](https://github.com/FredHutch/shiny-cromwell/assets/23532136/a6326bc4-4b33-4471-955d-821261efd959)

**Comment by vortexing** [comment]
Very easy fix.  Very low hanging fruit.  I wonder if Validate workflow and Troubleshoot workflow could go on the SAME tab as they are sort of QA sort of things?

**Comment by sitapriyamoorthi** [comment]
Since both these belong to different steps in running a workflow don't you think it would be more "logical" to have them as separate tabs? So the user isn't going back and forth?

**Comment by vortexing** [comment]
Depends on if people would rather flip through tabs or not.  Seems like a personal preference thing, or something to explore!

**Comment by sckott** [comment]
(handled in `getwilds/shiny-cromwell@dev`)

Okay, this isn't the final say of course, but here's a take screenshot below. I've split the validate and submit into separate tabs - nothing else has changed within those tabs. And it all still works. 

<img width="470" alt="Screenshot 2024-01-29 at 9 35 53 PM" src="https://github.com/FredHutch/shiny-cromwell/assets/577668/6419d9fc-81a7-4834-b0b8-0496e542ab78">
