### ISSUE TITLE
Dev UI: Date does not auto-populate to todays date

### ISSUE THREAD

**Issue by sitapriyamoorthi** [FredHutch/shiny-cromwell#180]
When tracking workflows the workflow list autopopulates to dates in the past. This means I have to go in and change the date to see the workflows that I just submitted

https://github.com/user-attachments/assets/5105138b-94a5-4e0f-b498-a9221cb97cb1

**Comment by sckott** [comment]
that is fixed in https://github.com/FredHutch/shiny-cromwell/pull/174 - waiting on @tefirman review

**Comment by tefirman** [comment]
Great call, closing now!
