### ISSUE TITLE
Dev UI: Add a link on the top bar to report issues

### ISSUE THREAD

**Issue by sitapriyamoorthi** [FredHutch/shiny-cromwell#184]
My recommendatio is to integrate the github repo where you want people to report issues into the top bar because this allows them to easily report issues irrespective of the page they are on. Rather than having to navigate to the last Help page and read a bunch of text!

**Comment by sckott** [comment]
In the old version of the app we did have it in the navbar under a dropdown, but moved it to a page. @codebeaker do you have a thought on this?

**Comment by sckott** [comment]
I'll have a think about this - explore options locally and see if a change maek sense

**Comment by sckott** [comment]
done on dev branch
