### ISSUE TITLE
Dev Ui: What are the units of time?

### ISSUE THREAD

**Issue by sitapriyamoorthi** [FredHutch/shiny-cromwell#186]
In the trackworkflows dont know if my workflow was running for 96.433 seconds or minutes! Helpful if that information was easily visible by either s or min?

**Comment by codebeaker** [comment]
agree that should be indicated with s or m. sorry for my part in that, i hadn't put that update in 1.2 because i thought it was going to be 1.3. but i should have put that in the mockups. thanks for pointing that out.

**Comment by sckott** [comment]
done on dev branch
