### ISSUE TITLE
Track Jobs on tracks activities of jobs submitted in "x" days

### ISSUE THREAD

**Issue by sitapriyamoorthi** [FredHutch/shiny-cromwell#19]
So the days history to display only shows the updates from jobs submitted. Would there be a way to make it such that it shows jobs that has any action on them form the last day or days indicated by the user?
![Screenshot 2023-12-14 at 10 15 34 AM](https://github.com/FredHutch/shiny-cromwell/assets/23532136/67cf6a78-8556-4af3-aba8-dc1d5caa246f)

**Comment by vortexing** [comment]
No, not easily.  To resolve this issue, we'd have to do a lot of logic work.  The days since submission is an easy API endpoint hence why that's the current button.  

Long term it'd be great to add more query types here but it's not a short term fix.

**Comment by tefirman** [comment]
This feels outside the scope of the v1.X improvements and potentially not worth the amount of effort it would require. Closing this as "wontfix".
