### ISSUE TITLE
Proof Login/logout 

### ISSUE THREAD

**Issue by sckott** [FredHutch/shiny-cromwell#21]
Right now I have just a simple button to login/out for PROOF

<img width="290" alt="Screenshot 2024-01-21 at 7 21 09 AM" src="https://github.com/FredHutch/shiny-cromwell/assets/577668/6cd0a307-6d9b-4f96-8cb3-a027291d5f24">

It's not great. I'm used to a login being in the top right of a navbar, and I think other people will be too. I haven't landed on anything that seems like a good fit yet. Some notes:

- An [SO solution](https://stackoverflow.com/a/63163205) to add the login/logout button in top right 
- package [shinyauthr](https://github.com/PaulC91/shinyauthr) - looks nice, but I think it won't work as I think it only works by checking user input username/password against a local data.frame, which won't work as we need to check against the proof API, but may be worth checking if we can just use the UI components
- https://www.polished.tech/ but it only does auth against their own cloud solution, so no go
- https://github.com/treysp/shiny_password
- heard from someone that mentioned https://github.com/r-lib/gargle/pull/157 & https://github.com/r-lib/httr2/issues/422 but even if those did help they aren't released yet
- https://datastorm-open.github.io/shinymanager/ is an option. apparently you can use a custom function to pass to the function that handles auth, so could try this. downside is that the framework "takes over the UI", so we may be limited in the UI if we use this
- a solution from Jason Bryer on mastodon https://gist.github.com/jbryer/d563b3147c7e5ea8c8d7910601676e39 - looks too complicated
- To surface some Slack discussion about this: There's not really any login solution we can adopt internally 
- others ...

**Comment by sckott** [comment]
Asked in the Posit forum for ideas

**Comment by sckott** [comment]
To surface some Slack discussion about this: _scott summarize any salient points here_

**Comment by sckott** [comment]
Currently going the route of forking `shinyauthr` and using a modified version of it for our login/logout flow. 

It's at https://github.com/getwilds/shinyauthr - changes are not pushed there yet but should be soon

Current issues not resolved:

- [ ] xxxx
- [ ] xxx

**Comment by tefirman** [comment]
@sckott -- Looks like you did some work on this in the commit from March 1st listed above and the login button is currently in the top right like you wanted. Would you consider this complete or is there still more work you'd like to do on it?

**Comment by sckott** [comment]
I think it can be closed, we have login that works. 

I'd definitely improve on this in v2 but we can open issues for that later
