### ISSUE TITLE
Access logs for prod and dev app

### ISSUE THREAD

**Issue by sckott** [FredHutch/shiny-cromwell#32]
Right now we (DaSL) can't see the logs from the prod and dev apps. Dan said it's something that could probably be done, but is not done yet. 

For now we can ping Dan with any log requests

**Comment by sckott** [comment]
- [ ] build logs are now available
- [ ] app logs coming

**Comment by tefirman** [comment]
DaSL now has access!
Shiny Logs: https://applogs.fredhutch.org/repo/shiny-cromwell
Build Logs: https://build-logs.fredhutch.org/project/39
Thanks @dtenenba !
