### ISSUE TITLE
Dev app: start and delete buttons on cromwell page disabled

### ISSUE THREAD

**Issue by sckott** [FredHutch/shiny-cromwell#36]
Even after logging in both buttons are disabled. Maybe it would help to see logs, but that's not possible right now. 

<img width="397" alt="Screenshot 2024-02-09 at 8 56 28 AM" src="https://github.com/FredHutch/shiny-cromwell/assets/577668/eeaa5c36-7bdb-4988-b341-42a40838f0af">

For now I'm reworking those buttons so they are by default enabled on login ...

<img width="364" alt="Screenshot 2024-02-09 at 9 02 05 AM" src="https://github.com/FredHutch/shiny-cromwell/assets/577668/6477e743-26d2-4a51-989e-bcfddbb29998">

... but if the user clicks start or delete then the disable/enable triggers, e.g. 

<img width="337" alt="Screenshot 2024-02-09 at 9 01 15 AM" src="https://github.com/FredHutch/shiny-cromwell/assets/577668/153e7d58-e9b3-4d52-99a5-b3afdd88a35a">

-----

**Goal:** get back to the original disable/enable based on login/server up status

**Comment by sckott** [comment]
removed code from server.R that was doing the work disabling/etc. in case come back to it later:

```r
# Hide or show start and stop buttons
  observe({
    if (!proof_loggedin(rv$token)) {
      shinyjs::disable(id = "cromwellStart")
      shinyjs::disable(id = "cromwellDelete")
    }
    if (!proof_serverup(rv$url, rv$token)) shinyjs::disable(id = "cromwellDelete")
    if (proof_loggedin_serverup(rv$url, rv$token)) {
      if (proof_status(token = rv$token)$canJobStart) {
        shinyjs::disable(id = "cromwellDelete")
      } else {
        shinyjs::disable(id = "cromwellStart")
      }
    }
  })
```

**Comment by tefirman** [comment]
Don't think this has been seen since March, potentially fixed by Scott's commits, closing.
