### ISSUE TITLE
Dev app: log in and server not up issues

### ISSUE THREAD

**Issue by sckott** [FredHutch/shiny-cromwell#38]
Fri (2024-02-09) morning:

- login flow was slow and not working for Sita at least, though worked for me, may have been transient
- Sita and I were getting a lot of server not up errors even though the status page said it was up

**Comment by sckott** [comment]
possibly related are these problems showing up in browser dev tools

<img width="1185" alt="Screenshot 2024-02-09 at 12 21 48 PM" src="https://github.com/FredHutch/shiny-cromwell/assets/577668/b5d94779-4c96-4b8a-b9a8-676833bf052a">

**Comment by avahoffman** [comment]
I was also getting a login issue too - nothing "broken" per se, but it only logged me in for a split second, then logged me out.

**Comment by sckott** [comment]
Thanks for reporting @avahoffman ! Did you eventually get logged in, or no?

**Comment by avahoffman** [comment]
@sckott Seems to be working now!

**Comment by sckott** [comment]
i think we're good now
