### ISSUE TITLE
Able to use other users' Cromwell Servers

### ISSUE THREAD

**Issue by tefirman** [FredHutch/shiny-cromwell#40]
Before starting my own cromwell server, I clicked the "Update Status" button to see what would happen and server details for Sita's cromwell instance popped up (see screenshot below). Not urgent, but might confuse future users.
![Screenshot 2024-02-12 at 3 47 40 PM](https://github.com/FredHutch/shiny-cromwell/assets/37599954/1deae294-48c1-485a-8348-ff0af45c97bf)

**Comment by tefirman** [comment]
I take it back, this might be a bigger issue, because when I tried to start my own cromwell server after that, it's telling me a job is already running:
![image](https://github.com/FredHutch/shiny-cromwell/assets/37599954/e619f403-c697-41f4-a6cb-18581507fafb)

**Comment by tefirman** [comment]
Looks like I can see all of her workflow runs in the "Track Jobs" tab, and even submit/abort jobs under her username (see "my_workflow" jobs in the screenshot below). Is only one person allowed to log in at a time for this dev prototype?
![image](https://github.com/FredHutch/shiny-cromwell/assets/37599954/b91e2577-d390-4cb7-ba02-3bde08775e56)
<img width="619" alt="image" src="https://github.com/FredHutch/shiny-cromwell/assets/37599954/d0494dcb-a2af-4661-b79c-fe02aae8140c">

**Comment by sckott** [comment]
Thanks @tefirman for reporting! Should be fixed now with 6672e46b90dd4be971ce8a3215e6e9a49da7fd0b
