### ISSUE TITLE
Switch between "Fred Hutch Cromwell" and FH Logo in header title?

### ISSUE THREAD

**Issue by tefirman** [FredHutch/shiny-cromwell#41]
Incredibly minor, but the “Fred Hutch Cromwell” title gets cut off to “Fre” when you close the side menu (see screenshot below). Probably not necessary for MVP, but it looks like it’s possible to switch between the title when open and a logo when closed based on this example:
- App: https://dgranjon.shinyapps.io/shinydashboardPlusDemo/
- Source Code (lines 9-11): https://github.com/RinteRface/shinydashboardPlus/blob/master/inst/examples/app.R

![image](https://github.com/FredHutch/shiny-cromwell/assets/37599954/55e697bf-08bd-4f6b-b9e4-901361cdc470)

**Comment by sckott** [comment]
thanks! I'll have a look - that also bothered me

**Comment by sckott** [comment]
(done in dev)
