### ISSUE TITLE
Singularity cache not created upon job submission

### ISSUE THREAD

**Issue by tefirman** [FredHutch/shiny-cromwell#44]
Unfortunately, any WDL job that uses a docker container is erroring out after submission due to the singularity cache directory not existing. As a demonstration, I deleted my entire cromwell-scratch directory to see if the appropriate folders would get recreated. I then submitted a hello-world-esque job, and cromwell-scratch was indeed recreated, but the ".singularity-cache" directory within it was not. The job ultimately failed due to a "no such file or directory" error message for ".singularity-cache" (see screenshot below).

![image](https://github.com/FredHutch/shiny-cromwell/assets/37599954/c26222f8-533f-414a-8ffd-3977dbdf978b)

**Comment by sckott** [comment]
thanks
