### ISSUE TITLE
Replace shinydashboard with bslib

### ISSUE THREAD

**Issue by sckott** [FredHutch/shiny-cromwell#49]
shinydashboard is stuck in bootstrap 3 and we're on bootstrap 5+ now. 

if it's relatively painless would be good to do

**Comment by tefirman** [comment]
@sckott -- How difficult would it be to test this update in dev? Might be smart to implement if it's not too painful since we're so far behind, but if it gets too sticky, we can wait until v2.0..

**Comment by sckott** [comment]
Well ..... I don't know how long before we'll replace shiny with the new JS thing. If its a year from now, then this would be worth it probably, but if it's 3-6 months from now then probably not. If we do think it's worth it then still would want to play a bit first to see how difficult or not to do

**Comment by sckott** [comment]
Playing with this on a local branch. May have something soon
