### ISSUE TITLE
Page refresh and re-login after starting server

### ISSUE THREAD

**Issue by sitapriyamoorthi** [FredHutch/shiny-cromwell#50]
Looks like I need to refresh the page to see the server "Status" update. But that makes me have to re-login

**Comment by sckott** [comment]
looking into this

**Comment by sckott** [comment]
@sitapriyamoorthi i think this is fixed now, can you please try again?

**Comment by sckott** [comment]
AFAICT this is fixed

**Comment by sitapriyamoorthi** [comment]
Yes! Works now!
