### ISSUE TITLE
Workflow timing not showing 

### ISSUE THREAD

**Issue by sitapriyamoorthi** [FredHutch/shiny-cromwell#51]
![Screenshot 2024-02-20 at 7 59 46 PM](https://github.com/FredHutch/shiny-cromwell/assets/23532136/bb85ba5a-e6f1-4f23-984a-780c58ce767a)

**Comment by sckott** [comment]
Can you give more details?  For how many days in the past? Any other important details? Was this for proof or non-proof?

**Comment by sitapriyamoorthi** [comment]
The app was hanging … a second login fixed it … it was PROOF loging . That’s why I closed the issue !

**Comment by sckott** [comment]
ah ok, will close again
