### ISSUE TITLE
Give me DIY as an option to start a new server once I delete PROOF generated server

### ISSUE THREAD

**Issue by sitapriyamoorthi** [FredHutch/shiny-cromwell#52]
After i delete my PROOF launched server. it would be nice to see the option for starting the server via DIY.  Would ideally like to see that DIY cromwell server button show up again!

**Comment by sitapriyamoorthi** [comment]
Alright i see it ... you can either log in through PROOF or DIY... wondering maybe if we could have just a log in and then options to start a server either using PROOF or DIY.

**Comment by sckott** [comment]
Hmm, I'm not sure it makes sense to provide a way to connect to a DIY server when you're logged in with PROOF. In big font at the top of the Cromwell Servers page it says 

**Manage Your PROOF Based Cromwell Server**

Which is pretty clear I think? 

But I could add some kind of note to that page telling users they can do a DIY if they logout and then enter their DIY url

**Comment by sitapriyamoorthi** [comment]
Sounds good! I think i added information in the PROOF 101 docs that will hopefully help! But we can additionally clarify that!
