### ISSUE TITLE
For DIY server kickoff need to default to add "http://" or change expected input format

### ISSUE THREAD

**Issue by sitapriyamoorthi** [FredHutch/shiny-cromwell#53]
Right now if I dont enter http://node:port it complains. But when kicking off my DIY server the string format is only node:port. not HTTP://node:port. It is a minor issue but would be nice for it to match the expected string that the DIY server gives.

**Comment by sckott** [comment]
Thanks Sita.

(from slack convo) It's hard to check that user input for a URL is valid if it's just the host and port. Also, perhaps it will be https at some point, or someone from outside of Hutch runs the app and uses https . So I figured we should just ask for the entire url.

I'll do a pull request to the diy repo to change the output if amy's okay with that

`rcromwell` also expects the http part

**Comment by sckott** [comment]
changes ready to go in diy repo, will open a PR and when that's merged will close this

**Comment by sckott** [comment]
pr here https://github.com/FredHutch/diy-cromwell-server/pull/28
