### ISSUE TITLE
Can launch two cromwell servers 

### ISSUE THREAD

**Issue by sitapriyamoorthi** [FredHutch/shiny-cromwell#54]
I can currently have two Cromwell servers running one made DIY and on via PROOF. I dont know how this managed in terms of resource allocation on the backend. Probably doesn't need to be addressed right away but just putting this here for future iterations.

**Comment by sitapriyamoorthi** [comment]
![Screenshot 2024-02-20 at 8 22 09 PM](https://github.com/FredHutch/shiny-cromwell/assets/23532136/2c3f7f22-46f4-4ff1-a1ce-8937b657a1e1)

**Comment by sckott** [comment]
Thanks Sita. Yeah there's nothing to do on this for now. I think scicomp is going to push people to proof route, but i imagine one will always be able to spin up a cromwell server DIY

**Comment by tefirman** [comment]
This isn't a big issue, and I imagine there won't be many people running DIY moving forward. Closing as "won'tfix".

**Comment by sitapriyamoorthi** [comment]
Just FYI in case of a PROOF outage we would potentially want a user to still be able to spin up a cromwell server and continue their work? We dont have support to constantly monitor and fix issues.
