### ISSUE TITLE
Convert "workflow" column of "Workflow Specific Job Information" to copy button

### ISSUE THREAD

**Issue by tefirman** [FredHutch/shiny-cromwell#56]
When looking at the details of a particular job in the "Workflow Specific Job Information" table, the "workflow" column displays the entire text of the WDL script which can get quite long. This unnecessarily increases the row height in the table which makes it harder to navigate and read (see screenshot below). I'm wondering if this would more useful as a "copy" button? Much like the "copyId" column in the "Workflows Run" table?

![image](https://github.com/FredHutch/shiny-cromwell/assets/37599954/0b32b2e0-e95e-4132-b31b-6f23142f9148)

**Comment by sckott** [comment]
Thanks for the reminder. I know we said we should do this before but has been forgotten.

**Comment by sckott** [comment]
@tefirman can you take another look at the app and see what you think wrt this specifc item?

**Comment by tefirman** [comment]
@sckott Looks great! Wondering if in the future we'll get similar requests about the "commandLine" column in the "Job List" table. If we do, the user in question is probably designing the task crappily, i.e. tasks are supposed to be relatively short snippets of code. Regardless, definitely not important for MVP. Thanks for implementing this!

**Comment by sckott** [comment]
Glad it works better now. 

Thanks for the note about the commandLine. Should come back to that later.
