### ISSUE TITLE
Add ability to see subworkflows (not just nested scatters)

### ISSUE THREAD

**Issue by vortexing** [FredHutch/shiny-cromwell#6]
Make a panel where the tasks from a subworkflow could be queried somehow.  Perhaps that's a better listing of their metadata in the main jobs list table, then another query box for the workflow ID for the subworkflow itself and a jobs table for that subworkflow?

**Comment by tefirman** [comment]
@vortexing -- Do you have an example that would harness this? Maybe a chromosome-scatter?
