### ISSUE TITLE
Track Jobs: Workflow name not getting repopulates in Workflow Description table

### ISSUE THREAD

**Issue by sitapriyamoorthi** [FredHutch/shiny-cromwell#64]
Looks like the "workflow_name" is not passing from the "Workflow Run" table to the "Workflow Description" table. See images below. 
![Screenshot 2024-02-24 at 7 05 53 AM](https://github.com/FredHutch/shiny-cromwell/assets/23532136/addeb836-285c-443f-9c6b-59bac6e5ee25)
![Screenshot 2024-02-24 at 7 05 39 AM](https://github.com/FredHutch/shiny-cromwell/assets/23532136/3e6a7b0a-c175-4915-9156-2e42b58c2941)

**Comment by sckott** [comment]
Thanks! I'll take a look

**Comment by sitapriyamoorthi** [comment]
This is still not working.

**Comment by sckott** [comment]
Thanks, haven't looked into it yet, will do
