### ISSUE TITLE
Nice to have: Dashboard showing aborted workflows

### ISSUE THREAD

**Issue by sitapriyamoorthi** [FredHutch/shiny-cromwell#65]
It would be nice to see also the number of workflows that get aborted so that the math adds up ! 
Not for this MVP but maybe in the future? 
![Screenshot 2024-02-25 at 9 42 49 AM](https://github.com/FredHutch/shiny-cromwell/assets/23532136/05da5aa5-2387-4705-aa21-fd3e7d65fe0c)

**Comment by sckott** [comment]
Thanks! Could, but then we'd have an odd number. Maybe there's a 6th thing that could be shown ...

**Comment by tefirman** [comment]
Feels unnecessary for v1.X considering the odd number conundrum, might want to revisit after v2.0, but marking as "won'tfix" for now.

**Comment by sitapriyamoorthi** [comment]
As a user running/troubleshooting through a WDL workflow it would ideally be nice to looks somewhere easily for workflows that have been aborted.

**Comment by sckott** [comment]
We should add this as a thing to add for proof v2 Sita
