### ISSUE TITLE
PROOF Server tab prettify?

### ISSUE THREAD

**Issue by sckott** [FredHutch/shiny-cromwell#72]
via https://github.com/FredHutch/shiny-cromwell/pull/66#discussion_r1505187625

I thought maybe we could tidy up this page a bit

**Comment by tefirman** [comment]
@sckott -- My gut says to leave that tab as-is since most of our documentation uses screenshots of the current state and we'll probably be changing it drastically in v2.0 anyways. Thoughts on closing this?

**Comment by sckott** [comment]
yeah close
