### ISSUE TITLE
Add new how to and WDL training material links

### ISSUE THREAD

**Issue by vortexing** [FredHutch/shiny-cromwell#77]
In the Resources section on the front we now have a how-to for PROOF in the Wiki and a WDL 101 class.

**Comment by sckott** [comment]
@vortexing include all  of these?

- product page https://sciwiki.fredhutch.org/datascience/proof/
- how to https://sciwiki.fredhutch.org/dasldemos/proof-how-to/ 
- 101 https://hutchdatascience.org/WDL_Workflows_Guide/
