### ISSUE TITLE
Add pre-check for active server connection

### ISSUE THREAD

**Issue by jayoung** [FredHutch/shiny-cromwell#8]
hey!

Here's a dumb user error that I bet will come up often - at least I will make this mistake myself often.

If you try to click 'validate workflow' or 'submit workflow' BEFORE you've done 'Connect to server'  (yes, I know I shouldn't do that but sometimes I forget I restarted my web browser, or maybe the connection times out), you get a very mysterious error:  "Error: An error has occurred. Check your logs or contact the app author for clarification".   

Is there a way to check whether the connection is active upon 'validate' or 'submit' and give a more informative error?   

And maybe, (this would be really nice), while a connection is active and alive, display something on the left toolbar that tells us we're actually connected (maybe display the connection name, e.g. gizmot32:8000)

thanks!

Janet

**Comment by sckott** [comment]
(handled in `dev` branch)
