### ISSUE TITLE
Add PROOF server start date

### ISSUE THREAD

**Issue by sitapriyamoorthi** [FredHutch/shiny-cromwell#80]
It would be nice to have a line here (see image below) that tells the user when they started their PROOF server. I know right now we cannot send an email when the users PROOF server ends. But atlease when we log in if we are able to see when the user started the server it would be helpful. 
![proof_server_start_date](https://github.com/FredHutch/shiny-cromwell/assets/23532136/915f8f08-2f78-426e-bbf3-fcb7d0ae41ed)

**Comment by sckott** [comment]
Good idea Sita, but I don't think the right information is returned in the PROOF API to allow for that. 

@dtenenba There's the server time, e.g. `7-0`, but we don't know when the server started. Is there some metadata that's easy to pass back in `GET /cromwell-server` that says how long until server time ends?

**Comment by dtenenba** [comment]
Yes, that could be done, and we could also send an email letting the user know when their server is about to expire. I'll look into adding this a little later. 

Not sure if I want to push this change before demo day though.

**Comment by dtenenba** [comment]
I took a look at this and this is actually in part of the code that I want to refactor.
I've opened an issue which is linked right above this comment. But let's keep this one open as well since the shiny app will need to be modified to display this information once it's available.

**Comment by sckott** [comment]
Sounds good, thanks

**Comment by dtenenba** [comment]
The API GET /cromwell-server endpoint now returns something like this:

```json
{
  "canJobStart": false,
  "jobStatus": "RUNNING",
  "cromwellUrl": "https://gizmok8.fhcrc.org:34047/",
  "jobStartTime": "2024-04-15T13:16:36",
  "jobEndTime": "2024-04-22T13:16:36",
  "jobInfo": {
    "WORKFLOWLOGDIR": "/home/dtenenba/.cromwell/workflow-logs",
    "SCRATCHDIR": "/fh/scratch/delete90/_ADM/SciComp/user/dtenenba/cromwell-scratch",
    "SLURM_JOB_ID": "40462969",
    "CROMWELL_DIR": "/home/dtenenba/.cromwell",
    "SERVERLOGDIR": "/home/dtenenba/.cromwell/server-logs",
    "SINGULARITYCACHEDIR": "/fh/scratch/delete90/_ADM/SciComp/user/dtenenba/cromwell-scratch/.singularity-cache",
    "SERVERTIME": "7-0",
    "USE_AWS": null,
    "SLURM_JOB_ACCOUNT": "scicomp"
  }
}

Note the new `jobStartTime` and `jobEndTime` fields.

This is the info you will need to incorporate this into the shiny app.

```

**Comment by dtenenba** [comment]
Seattle time.

**Comment by dtenenba** [comment]
Should the time zone be included / should this be in a standard format like ISO8601? What you see here is exactly what slurm produces. 
But I am thinking it makes sense to make it a standard format to make it more easily parseable by R/python/whatever. And having no time zone makes it ambiguous.

**Comment by seankross** [comment]
You will never get an argument from me against ISO8601, if that's what's coming from the API then I could make the display text prettier.
