### ISSUE TITLE
Add button to clear Singularity Cache?

### ISSUE THREAD

**Issue by tefirman** [FredHutch/shiny-cromwell#84]
Pretty specific use-case but might be worth considering:
- User runs a pipeline that utilizes their own custom Docker image.
- Copy of the image gets pulled to the singularity cache.
- User notices a mistake in the build of that Docker image, fixes the mistake, and repushes it to DockerHub using the same tag.
- Upon resubmission, PROOF uses the old image from the cache rather than pulling a new copy from DockerHub, and the same error pops up, thoroughly confusing the user.

Potential solution: adding a button in the "Troubleshoot" tab that deletes all existing images in the user's singularity cache upon clicking?

**Comment by sckott** [comment]
Thanks @tefirman 

Do you know if someone was doing this without a GUI like this app, would they be able to specify in the WDL or a settings file to not use old images? Cause then they could simply update their files they upload here. If not, then yeah maybe something configureable in the app

**Comment by sckott** [comment]
ping @tefirman

**Comment by tefirman** [comment]
This feels like a pretty rare scenario (i.e. only occurs with GHCR containers) and outside the scope of v1.X updates. Potentially worth revisiting after v2.0, but closing for now.
