### ISSUE TITLE
Differing numbers of rows error

### ISSUE THREAD

**Issue by sckott** [FredHutch/shiny-cromwell#85]
add details ...

**Comment by sckott** [comment]
tl;dr leaving it for now - until someone has the time to fix

This happens when we call `rcromwell::cromwell_workflow` and what's returned from the fxn is a list where it can't easily be converted into a data.frame. We're doing a bunch of processing on the data returned from the Cromwell API in the `rcromwell::cromwell_workflow` function (See https://github.com/getwilds/rcromwell/blob/main/R/cromwellWorkflow.R) so perhaps it should be handled there - that is, cleaning up the output from the fxn so it's always a tibble and not a list sometimes

**Comment by dtenenba** [comment]
Here's a screenshot.

![image](https://github.com/FredHutch/shiny-cromwell/assets/2286826/ae0b211a-8027-4df5-8784-596863da1268)

**Comment by sckott** [comment]
Looking at this now. The problem we're faced with is that `inputs` object in the output from gathering metadata on a single workflow can be shaped in many, many different ways. Currently in the shiny app we're trying to show `inputs` as a table/data.frame. I'm not sure we can show a meaningful representation of `inputs` as a table since we'd have to force a bunch of metadata that aren't related to each other into the same rows. 

Asking in slack what folks think

**Comment by sckott** [comment]
After discussion in slack decided that 

- at least some people do have a need for VIEWING this data in the app (vs. just clicking to copy/paste in a text editor outside the app)
- we'd test out some options for viewing the data in the app
  - https://github.com/timelyportfolio/listviewer via Dan
  - others?
- if the viewing actual data options don't work then just provide a download button
