### ISSUE TITLE
Need GPU accessible on PROOF

### ISSUE THREAD

**Issue by Sanaz01** [FredHutch/shiny-cromwell#87]
Hi, 
I am trying to run tools on Gizmo that require GPU. When using module load feature directly on Gizmo CMD, it works perfectly fine. However, when submitting WDL workflows (that use docker for packages) using PROOF. I get the error: (I do get output but using CPU)
```dockerfile
An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.
```
When submitting WDL workflows (that use modules) using PROOF. I get the error:
```dockerfile
sbatch: error: Unable to open file

**Comment by tefirman** [comment]
Fixed in [recent proof-api PR](https://github.com/FredHutch/proof-api/pull/44) for PROOF v1.0. See [this basic test workflow](https://github.com/getwilds/ww-test-workflows/blob/main/gpuMatrixMult/gpuMatrixMult.wdl) for an example of how to execute GPU tasks.
