### ISSUE TITLE
need to stress test

### ISSUE THREAD

**Issue by dtenenba** [FredHutch/shiny-cromwell#96]
During a user interview, the production instance froze up. Scaled to 4 replicas but need to determine the underlying cause. 

We should test a non-prod instance with multiple simultaneous users.

Maybe related to #89 - just guessing.

**Comment by dtenenba** [comment]
Also the prod app greys out after a few minutes of inactivity. If you reload, you have to log in again. Those are maybe 2 separate issues but they combine to add up to inconvenience. If the app is going to gray out, at least it should remember your login (using cookies?). 
But it really should not gray out.

**Comment by tefirman** [comment]
- Held a user-based stress test on 7/17/24 where five separate users opened instances of PROOF and tried submitting/tracking jobs.
- Biggest issues that popped up were #111 and #113
- Both issues are resolved by refreshing the screen and logging back in (although greying out pops back up soon after if traffic is still high)
- In the future (potentially v2.0), it would be a good idea to automate this kind of stress test (will create new issue), but going to close this one for now
