### ISSUE TITLE
Loaded without it's guts

### ISSUE THREAD

**Issue by vortexing** [FredHutch/shiny-cromwell#97]
<img width="818" alt="Screenshot 2024-05-19 at 7 50 36 PM" src="https://github.com/FredHutch/shiny-cromwell/assets/13182518/609c3ce2-0aa4-4422-be01-84642c90be79">
Not sure what happened here - 7:52pm on 5/19 - shouldn't have been a busy time.

**Comment by sckott** [comment]
@vortexing Has this happened again since this one occasion?

**Comment by tefirman** [comment]
This happened to me again a couple weeks ago. I'll make sure to provide more details next time it happens again!

**Comment by sckott** [comment]
I can't reproduce this and I can't think of a way to emulate this situation. 

@dtenenba Can I get app logs surrounding this time Amy mentions above:

> what happened here - 7:52pm on 5/19 - shouldn't have been a busy time.

**Comment by dtenenba** [comment]
I don't see anything at that time:

https://applogs.fredhutch.org/repo/shiny-cromwell?page=-667

It goes from 2024-05-19 14:22:19 to 2024-05-20 09:35:19.

But I am not exactly sure whether those timestamps are local time or UTC or something - need to confirm that. If you go to the previous page ( https://applogs.fredhutch.org/repo/shiny-cromwell?page=-668 ) you see some warnings. And the page before that ( https://applogs.fredhutch.org/repo/shiny-cromwell?page=-669 ) .
It seems these warnings are pretty common - this may be a red herring.

**Comment by tefirman** [comment]
Going to close this since we can't seem to reliably recreate it. If I remember right, refreshing the page seems to alleviate this so I'm not too worried about it, but we can always reopen if it pops up again. Thanks @dtenenba and @sckott for taking a look!

**Comment by sckott** [comment]
Thanks for looking into it @dtenenba
