### ISSUE TITLE
file uploads having a strange issue 

### ISSUE THREAD

**Issue by vortexing** [FredHutch/shiny-cromwell#98]
<img width="967" alt="Screenshot 2024-05-19 at 7 44 55 PM" src="https://github.com/FredHutch/shiny-cromwell/assets/13182518/33e0e0ff-675a-4b90-a9b4-c05b5e7c9d2d">
Also not really sure what happened here but I was not able to submit b/c I'd forgotten that my server was down.

**Comment by vortexing** [comment]
<img width="1097" alt="Screenshot 2024-05-19 at 7 58 14 PM" src="https://github.com/FredHutch/shiny-cromwell/assets/13182518/f3d75dfc-a4c3-4bf9-b1c5-ddb7df8e3770">
Was unable to submit when the server was actually up.  But strangely the files it grumped about were different.

**Comment by dtenenba** [comment]
It is possible this is related to #102 in that this is a stateful app that is sometimes talking to different replicas without stickiness. So it could be fixed by #103 .
